server:
  port: 8080
spring:
  kafka:
    defaultBrokerPort: 9092
    bootstrap-servers: '192.168.99.103:9092'
  datasource:
    url: 'jdbc:mysql://192.168.99.103/teste?useSSL=false'
    username: root
    password: teste
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'

  cloud:
    stream:
      bindings:
        output:
          group-id: 'comunicacao'
          destination: 'assinatura-comunicacao'
          content-type: application/json
      kafka:
        binder:
          brokers: 192.168.99.103:9092
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
