server:
  port: 8080
spring:
  kafka:
    defaultBrokerPort: 9092
    bootstrap-servers: 'kafka:9092'

  cloud:
    stream:
      default:
        producer:
          useNativeEncoding: true
      bindings:
        output:
          destination: 'assinatura-comunicacao'
          content-type: application/json
      kafka:
        binder:
          brokers: 'kafka:9092'
          producer-properties:
            key.serializer: 'org.apache.kafka.common.serialization.StringSerializer'
            value.serializer: 'org.springframework.kafka.support.serializer.JsonSerializer'
