version: "3"
services:
    db:
        image: mysql
        container_name: "mysql"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
        - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: teste
            MYSQL_DATABASE: teste
        volumes:
            - ./db/MySql:/var/lib/mysql
#        volumes:
#            - ./db/MySql:/var/lib/mysql
    zookeeper:
        image: bitnami/zookeeper:latest
        container_name: "zookeeper"
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: bitnami/kafka:latest
        container_name: "kafka"
        ports:
            - "9092:9092"
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.99.103:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
        extra_hosts:
            - "192.168.99.103:127.0.0.1"
#    gateway:
#        container_name: "gateway"
#        image: amd64/gradle:jdk14
#        volumes:
#            - ./assinar:/home/gateway
#        working_dir: /home/gateway
#        command: ["./gradlew", "bootRun"]
#        depends_on:
#            - db
#            - kafka
#            - zookeeper
#        restart: always
#    cad-client:
#        container_name: "cad-client"
#        image: amd64/gradle:jdk14
#        volumes:
#            - ./cad-client:/home/cad-client
#        working_dir: /home/cad-client
#        ports:
#            - "80:8080"
#        command: ["./gradlew", "bootRun"]
#        depends_on:
#            - db
#            - kafka
#            - zookeeper
#        restart: always
#    com-assinatura:
#        container_name: "com-assinatura"
#        image: amd64/gradle:jdk14
#        volumes:
#            - ./com-assinatura:/home/com-assinatura
#        working_dir: /home/com-assinatura
#        command: ["./gradlew", "bootRun"]
#        depends_on:
#            - kafka
#            - zookeeper
#        restart: always
#    assinar:
#        container_name: "assinar"
#        image: amd64/gradle:jdk14
#        volumes:
#            - ./assinar:/home/assinar
#        working_dir: /home/assinar
#        ports:
#            - "6668:8082"
#        command: ["./gradlew", "bootRun"]
#        depends_on:
#            - db
#            - kafka
#            - com-assinatura
#        restart: always
#    processar-pagamento:
#        container_name: "processar-pagamento"
#        image: amd64/gradle:jdk14
#        volumes:
#            - ./processar-pagamento:/home/processar-pagamento
#        working_dir: /home/processar-pagamento
#        ports:
#            - "6669:8083"
#        command: ["./gradlew", "bootRun"]
#        depends_on:
#            - db
#            - kafka
#            - assinar
#        restart: always
#    finaliza-pagamento:
#        container_name: "finaliza-pagamento"
#        image: amd64/gradle:jdk14
#        volumes:
#            - ./finaliza-pagamento:/home/finaliza-pagamento
#        working_dir: /home/finaliza-pagamento
#        ports:
#            - "6670:8084"
#        command: ["./gradlew", "bootRun"]
#        depends_on:
#            - db
#            - kafka
#            - processar-pagamento
#        restart: always
