version: "3"
services:
    db:
        image: mysql
        container_name: "mysql"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
        - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: teste
            MYSQL_DATABASE: teste
#        volumes:
#            - ./db/MySql:/var/lib/mysql
    zookeeper:
        image: bitnami/zookeeper:latest
        container_name: "zookeeper"
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: bitnami/kafka:latest
        container_name: "kafka"
        ports:
            - "9092:9092"
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
    cad-client:
        container_name: "cad-client"
        image: amd64/gradle:jdk14
        volumes:
            - ./cad-client:/home/cad-client
        working_dir: /home/cad-client
        ports:
            - "80:8080"
        command: ["./gradlew", "bootRun"]
        depends_on:
            - db
            - kafka
            - zookeeper
        restart: always