spring:
  kafka:
    defaultBrokerPort: 9092
    bootstrap-servers: 'kafka:9092'

  cloud:
    stream:
      default:
        consumer: true
      bindings:
        input:
          destination: 'assinatura-finalizar'
          binder: 'kafka'
          content-type: application/json
      kafka:
        binder:
          brokers: 'kafka:9092'
          consumer-properties:
            key-deserializer: 'org.apache.kafka.common.serialization.StringDeserializer'
            value-deserializer: 'org.apache.kafka.common.serialization.JsonDeserializer'