spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
server:
  port: 8099


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    lease-renewal-interval-in-seconds: 5

zuul:
  routes:
    cad-cliente:
      sensitiveHeaders:
      path: /api/request-assinar/**
      url: http://cad-client:8080/
    assinar:
      sensitiveHeaders:
      path: /api/request-cad-client/**
      url: http://assinar:8082/



