spring:
  kafka:
    defaultBrokerPort: 9092
    bootstrap-servers: '192.168.99.103:9092'
    consumer:
      group-id: 'comunicacao'
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'


  cloud:
    stream:
      default:
        consumer:
          useNativeEncoding: true
      bindings:
        input:
          destination: 'assinatura-comunicacao'
          content-type: application/json
      kafka:
        binder:
          brokers: 192.168.99.103:9092
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer