spring:
  kafka:
    defaultBrokerPort: 9092
    bootstrap-servers: 'kafka:9092'

cloud:
  stream:
    default:
      producer: true
    bindings:
      output:
        destination: 'assinatura-finalizar'
        binder: 'kafka'
        content-type: application/json
      input:
        destination: 'assinatura-processar'
        binder: 'kafka'
        content-type: application/json
    kafka:
      binder:
        brokers: 'kafka:9092'
        producer-properties:
          key-deserializer: 'org.apache.kafka.common.serialization.StringSerializer'
          value-deserializer: 'org.apache.kafka.common.serialization.JsonSerializer'
        consumer-properties:
          key-deserializer: 'org.apache.kafka.common.serialization.StringDeserializer'
          value-deserializer: 'org.apache.kafka.common.serialization.JsonDeserializer'

